"""Deploy and run generated mini-apps for Kanban cards."""

from __future__ import annotations

import socket
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from app.agents.schemas import AppFile, ImplementationResult
from app.models.contracts import TaskCard

ROOT = Path(__file__).resolve().parents[2]
WORKSPACES = ROOT / "workspaces"


@dataclass
class RuntimeProcess:
    card_id: str
    port: int
    process: subprocess.Popen
    kind: str
    preview_url: str


_processes: dict[str, RuntimeProcess] = {}


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def workspace_for(card_id: str) -> Path:
    path = WORKSPACES / card_id
    path.mkdir(parents=True, exist_ok=True)
    return path


def stop_runtime(card_id: str) -> None:
    current = _processes.pop(card_id, None)
    if not current:
        return
    try:
        current.process.terminate()
        current.process.wait(timeout=3)
    except Exception:
        try:
            current.process.kill()
        except Exception:
            pass


def stop_all_runtimes() -> int:
    """Terminate every running mini-app. Returns how many were stopped."""
    count = 0
    for card_id in list(_processes.keys()):
        stop_runtime(card_id)
        count += 1
    return count


def clear_workspaces() -> None:
    """Remove all generated app files so they can be regenerated cleanly."""
    import shutil

    if not WORKSPACES.exists():
        return
    for child in WORKSPACES.iterdir():
        try:
            if child.is_dir():
                shutil.rmtree(child, ignore_errors=True)
            else:
                child.unlink(missing_ok=True)
        except Exception:
            pass


def write_app_files(card_id: str, files: list[AppFile]) -> Path:
    root = workspace_for(card_id)
    # clean previous non-hidden files lightly
    for existing in root.glob("*"):
        if existing.is_file():
            existing.unlink()
    for file in files:
        safe = Path(file.path)
        if safe.is_absolute() or ".." in safe.parts:
            continue
        target = root / safe
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(file.content, encoding="utf-8")
    return root


def ensure_fallback_app(card: TaskCard, implementation: ImplementationResult) -> ImplementationResult:
    """If the LLM omitted files, ship a minimal working HTML app."""
    if implementation.app_files:
        return implementation
    title = card.title.replace("<", "").replace(">", "")
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <style>
    :root {{ font-family: Inter, system-ui, sans-serif; color: #0f172a; background: #f8fafc; }}
    body {{ margin: 0; min-height: 100vh; display: grid; place-items: center; }}
    .card {{ width: min(520px, 92vw); background: white; border: 1px solid #e2e8f0; border-radius: 20px; padding: 28px; box-shadow: 0 20px 40px rgba(15,23,42,.08); }}
    h1 {{ margin: 0 0 8px; font-size: 1.6rem; }}
    p {{ color: #64748b; line-height: 1.5; }}
    button {{ margin-top: 16px; border: 0; background: #2563eb; color: white; border-radius: 12px; padding: 10px 14px; font-weight: 700; cursor: pointer; }}
    #out {{ margin-top: 14px; font-weight: 600; color: #059669; }}
  </style>
</head>
<body>
  <main class="card">
    <h1>{title}</h1>
    <p>Generated by Manus SwarmDesk agents and deployed for live preview.</p>
    <p>{implementation.summary}</p>
    <button id="go">Run demo action</button>
    <div id="out"></div>
  </main>
  <script>
    document.getElementById('go').onclick = () => {{
      document.getElementById('out').textContent = 'App is live at ' + new Date().toLocaleTimeString();
    }};
  </script>
</body>
</html>
"""
    implementation.app_kind = "static"
    implementation.entrypoint = "index.html"
    implementation.app_files = [AppFile(path="index.html", content=html)]
    implementation.files_changed = ["index.html"]
    return implementation


def deploy_app(card: TaskCard, implementation: ImplementationResult) -> TaskCard:
    implementation = ensure_fallback_app(card, implementation)
    stop_runtime(card.id)
    root = write_app_files(card.id, implementation.app_files)
    port = _free_port()
    kind = (implementation.app_kind or "static").lower()

    if kind == "fastapi" and (root / "main.py").exists():
        proc = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "uvicorn",
                "main:app",
                "--host",
                "127.0.0.1",
                "--port",
                str(port),
            ],
            cwd=str(root),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    else:
        # static site
        if not (root / "index.html").exists() and implementation.app_files:
            # rename first html-like file
            first = implementation.app_files[0]
            (root / "index.html").write_text(first.content, encoding="utf-8")
        proc = subprocess.Popen(
            [sys.executable, "-m", "http.server", str(port), "--bind", "127.0.0.1"],
            cwd=str(root),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    preview = f"http://127.0.0.1:{port}/"
    _processes[card.id] = RuntimeProcess(
        card_id=card.id,
        port=port,
        process=proc,
        kind=kind,
        preview_url=preview,
    )
    card.preview_url = preview
    card.runtime_port = port
    card.runtime_status = "running"
    return card


def runtime_info(card_id: str) -> dict | None:
    item = _processes.get(card_id)
    if not item:
        return None
    alive = item.process.poll() is None
    return {
        "card_id": card_id,
        "port": item.port,
        "preview_url": item.preview_url,
        "kind": item.kind,
        "status": "running" if alive else "stopped",
    }
